name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Deploy documentation
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          mike deploy --push --update-aliases latest
        elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          version=${GITHUB_REF#refs/tags/v}
          mike deploy --push --update-aliases $version latest
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}